#!/bin/bash

echo "🚀 Jira Clone Complete Workflow Tests 🚀"
echo "======================================="

echo ""
echo "🛠️ The npm scripts don't work properly due to TypeScript loading issues."
echo "Use these DIRECT commands instead:"
echo ""

echo "✅ WORKING COMMANDS:"
echo "==================="
echo ""
echo "1. Basic Functionality Test:"
echo "   HEADLESS=true node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/basic-functionality.feature"
echo ""
echo "2. Complete Workflow Test:"
echo "   HEADLESS=true node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/complete-jira-workflow.feature"
echo ""
echo "3. Project Creation Test:"
echo "   HEADLESS=true node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/complete-project-workflow.feature --tags '@project-creation'"
echo ""
echo "4. With Specific Tags:"
echo "   HEADLESS=true node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/complete-jira-workflow.feature --tags '@epic-linking'"
echo ""
echo "5. See Browser (Non-Headless):"
echo "   node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/basic-functionality.feature"
echo ""

echo "🏃‍♂️ Running Basic Functionality Test:"
echo "======================================"
HEADLESS=true node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/basic-functionality.feature

echo ""
echo "✅ Basic Test Complete!"
echo ""

echo "🏃‍♂️ Running Complete Workflow Test:"
echo "===================================="
HEADLESS=true node_modules/.bin/cucumber-js --require-module ts-node/register --require 'step-definitions/**/*.ts' --require 'support/**/*.ts' features/complete-jira-workflow.feature --tags "@complete-workflow"

echo ""
echo "✅ All Tests Complete!"
echo ""
echo "📖 What Was Tested:"
echo "=================="
echo "   ✅ Project creation via UI"
echo "   ✅ Different issue types (Epic, Story, Task, Bug)"
echo "   ✅ Epic linking to tasks/stories"
echo "   ✅ Sprint creation and management"
echo "   ✅ Time logging on tasks"
echo "   ✅ Task workflow (To Do → In Progress → Done)"
echo "   ✅ Sprint completion"
echo "   ✅ Reports verification"
echo ""
echo "💡 Use the direct commands above for best results!"
echo ""